### PR TITLE
NEW: Add static C++ library for Linux

### PR DESCRIPTION
**Pull request by rodneyp290**
After going over Linux install instructions from scratch with @jakerenzella, I realised C++ wasn't compiling anymore as the compiler couldn't find `-lSplashKitCPP (libSplashKitCPP.a)`.  I ended up solving it by copying the `ibSplashKitCPP.a` generated by the [splashkit-core](https://github.com/splashkit/splashkit-core) repo scripts.
When discussing with Jake, he explained that this file is meant to be generated and uploaded to the repo, rather than made by be skm cmake. Is this correct?

### CODE REVIEW

**Comment by rodneyp290** [comment]
I also had a go at implementing `skm linux install` last night (SEE: [my enhance/linux-install-script/ branch](https://github.com/rodneyp290/skm/blob/enhance/linux-install-script/linux/install/install.sh).
Should I rebase that on here, and then make one PR?

**Comment by macite** [comment]
That would be great 👍

**Comment by macite** [comment]
Actually, we should approach this differently. We need the CPP cmake file in the source as well... so that they can build this library themselves.

**Comment by rodneyp290** [comment]
I'm taking that you mean that this static lib shouldn't be a part of the repo, and this PR should be closed?

**Comment by macite** [comment]
Yes - lets get Linux users to build this themselves.

**Pull request closed without merging**
